//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Status
    {
        public Cat_Status()
        {
            this.Cat_Recurso = new HashSet<Cat_Recurso>();
            this.Cat_TipoRecursos = new HashSet<Cat_TipoRecursos>();
            this.Cat_Ubicacion = new HashSet<Cat_Ubicacion>();
            this.Empresa = new HashSet<Empresa>();
            this.Mensaje = new HashSet<Mensaje>();
            this.Notificacion = new HashSet<Notificacion>();
            this.Reserva = new HashSet<Reserva>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IDStatus { get; set; }
        public string DescStatus { get; set; }
    
        public virtual ICollection<Cat_Recurso> Cat_Recurso { get; set; }
        public virtual ICollection<Cat_TipoRecursos> Cat_TipoRecursos { get; set; }
        public virtual ICollection<Cat_Ubicacion> Cat_Ubicacion { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<Mensaje> Mensaje { get; set; }
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
