//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_TipoRecursos
    {
        public Cat_TipoRecursos()
        {
            this.Cat_Recurso = new HashSet<Cat_Recurso>();
        }
    
        public int IDTipoRecurso { get; set; }
        public string DescTipoRecurso { get; set; }
        public int IDStatus { get; set; }
        public int IDEmpresa { get; set; }
    
        public virtual ICollection<Cat_Recurso> Cat_Recurso { get; set; }
        public virtual Cat_Status Cat_Status { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
