//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Cat_Recurso = new HashSet<Cat_Recurso>();
            this.Cat_TipoRecursos = new HashSet<Cat_TipoRecursos>();
            this.Cat_Ubicacion = new HashSet<Cat_Ubicacion>();
            this.Reserva = new HashSet<Reserva>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IDEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Dominio { get; set; }
        public string Contacto { get; set; }
        public int IDStatus { get; set; }
    
        public virtual ICollection<Cat_Recurso> Cat_Recurso { get; set; }
        public virtual Cat_Status Cat_Status { get; set; }
        public virtual ICollection<Cat_TipoRecursos> Cat_TipoRecursos { get; set; }
        public virtual ICollection<Cat_Ubicacion> Cat_Ubicacion { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
