//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int IDMensaje { get; set; }
        public int IDRemitente { get; set; }
        public int IDDestinatario { get; set; }
        public string DescMensaje { get; set; }
        public int IDNotificacion { get; set; }
        public int IDStatus { get; set; }
    
        public virtual Cat_Status Cat_Status { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
